name: Update statuses
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * *'
env:
  MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
  MASTODON_SERVER_URL: ${{ secrets.MASTODON_SERVER_URL }}
  MASTODON_ACCOUNT_ID: ${{ secrets.MASTODON_ACCOUNT_ID }}
jobs:
  update-tweets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run update-statuses
      - name: Check for meaningful changes
        id: check-changes
        run: |
          # Check if README.md has changes other than just the timestamp
          if git diff --quiet HEAD -- README.md; then
            echo "No changes to README.md"
            echo "has-changes=false" >> $GITHUB_OUTPUT
          else
            # Get the diff and check if it's only timestamp changes
            diff_output=$(git diff HEAD -- README.md)
            # Check if the only changes are to lines containing "Last updated"
            # Filter out diff headers (---, +++, @@) and look for actual content changes
            meaningful_changes=$(echo "$diff_output" | grep -E '^[-+][^-+@]' | grep -v -E '_Last updated.*UTC\._' || true)
            if [ -n "$meaningful_changes" ]; then
              echo "Meaningful changes detected in README.md"
              echo "has-changes=true" >> $GITHUB_OUTPUT
            else
              echo "Only timestamp changes detected in README.md"
              echo "has-changes=false" >> $GITHUB_OUTPUT
            fi
          fi
      - uses: stefanzweifel/git-auto-commit-action@v7
        if: steps.check-changes.outputs.has-changes == 'true'
        with:
          commit_message: Update statuses
          branch: main
          file_pattern: README.md
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
